// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHOG3qkZO9XAX-w9Nq6TBd-mSqr1rGc0o',
    appId: '1:954438484545:web:e4e3a808f4564191927cc0',
    messagingSenderId: '954438484545',
    projectId: 'cvcraft-b31c3',
    authDomain: 'cvcraft-b31c3.firebaseapp.com',
    storageBucket: 'cvcraft-b31c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoZFGfFtP2dwmmAxEyMteCXSmQwG_vsNs',
    appId: '1:954438484545:android:eedada4310e92758927cc0',
    messagingSenderId: '954438484545',
    projectId: 'cvcraft-b31c3',
    storageBucket: 'cvcraft-b31c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBtDkaiQ6u5Y1J7FB2Jc62K5xpey0hk_4',
    appId: '1:954438484545:ios:0e7eca573c38464a927cc0',
    messagingSenderId: '954438484545',
    projectId: 'cvcraft-b31c3',
    storageBucket: 'cvcraft-b31c3.appspot.com',
    iosBundleId: 'com.example.jobsLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBtDkaiQ6u5Y1J7FB2Jc62K5xpey0hk_4',
    appId: '1:954438484545:ios:0e7eca573c38464a927cc0',
    messagingSenderId: '954438484545',
    projectId: 'cvcraft-b31c3',
    storageBucket: 'cvcraft-b31c3.appspot.com',
    iosBundleId: 'com.example.jobsLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHOG3qkZO9XAX-w9Nq6TBd-mSqr1rGc0o',
    appId: '1:954438484545:web:53fe518981c3a0b6927cc0',
    messagingSenderId: '954438484545',
    projectId: 'cvcraft-b31c3',
    authDomain: 'cvcraft-b31c3.firebaseapp.com',
    storageBucket: 'cvcraft-b31c3.appspot.com',
  );
}
