// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqKe_8d-CBWIY0m6S8gzoLjY5DT01jZWc',
    appId: '1:756567732277:web:ff624103d7effec70ec17c',
    messagingSenderId: '756567732277',
    projectId: 'resume-builder-e64b2',
    authDomain: 'resume-builder-e64b2.firebaseapp.com',
    storageBucket: 'resume-builder-e64b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqy6w76fWjkxTBdi1pR1l9rgg5nl-mI-A',
    appId: '1:756567732277:android:c4bfbf83350e168b0ec17c',
    messagingSenderId: '756567732277',
    projectId: 'resume-builder-e64b2',
    storageBucket: 'resume-builder-e64b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4EAEPrJvaDXvhvd3hC6dAFbphD-jSLNM',
    appId: '1:756567732277:ios:7af092a0cfddf9ec0ec17c',
    messagingSenderId: '756567732277',
    projectId: 'resume-builder-e64b2',
    storageBucket: 'resume-builder-e64b2.appspot.com',
    iosBundleId: 'com.example.jobsLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4EAEPrJvaDXvhvd3hC6dAFbphD-jSLNM',
    appId: '1:756567732277:ios:7af092a0cfddf9ec0ec17c',
    messagingSenderId: '756567732277',
    projectId: 'resume-builder-e64b2',
    storageBucket: 'resume-builder-e64b2.appspot.com',
    iosBundleId: 'com.example.jobsLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqKe_8d-CBWIY0m6S8gzoLjY5DT01jZWc',
    appId: '1:756567732277:web:40cac383f0decf0c0ec17c',
    messagingSenderId: '756567732277',
    projectId: 'resume-builder-e64b2',
    authDomain: 'resume-builder-e64b2.firebaseapp.com',
    storageBucket: 'resume-builder-e64b2.appspot.com',
  );
}
